### ISSUE TITLE
[BUG]: bad icons

### ISSUE THREAD

**Issue by zenby** [memory-cards/enki-parser#1]
There were a lot of cards with icons at enki repository. 
Unfortunately these all icons looks in the same way:

![image](https://user-images.githubusercontent.com/32563455/55483576-86692480-562f-11e9-9bc4-fab27f696b7b.png)

I believe it's because of encoding of these images:
For example [here ](https://github.com/memory-cards/cards/blob/af15cf4030dc8bfe6214b09d869705fe9951731a/enki/html/computer-code/intro-pre-0.json5) we have this `img` tag with **url-encoded** src attribute. 
```
<img src="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22320%22%20height%3D%2292%22%3E%3Cg%20fill%3D%22none%22%20fill-rule%3D%22evenodd%22%3E%3Crect%20width%3D%22320%22%20height%3D%2292%22%20fill%3D%22%23FFF%22%20rx%3D%229%22%2F%3E%3Ctext%20fill%3D%22%23000%22%20font-family%3D%22Courier%22%20font-size%3D%2216%22%3E%3Ctspan%20x%3D%2218%22%20y%3D%2232%22%3E%20.enki-highlight%20%7B%3C%2Ftspan%3E%20%3Ctspan%20x%3D%2218%22%20y%3D%2251%22%3E%20color%3A%20%23F46C43%3B%3C%2Ftspan%3E%20%3Ctspan%20x%3D%2218%22%20y%3D%2270%22%3E%20%7D%3C%2Ftspan%3E%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="pre-element">
```
After encoding of this attribute we will get
```
<svg xmlns="http://www.w3.org/2000/svg" width="320" height="92"><g fill="none" fill-rule="evenodd"><rect width="320" height="92" fill="#FFF" rx="9"/><text fill="#000" font-family="Courier" font-size="16"><tspan x="18" y="32"> .enki-highlight {</tspan> <tspan x="18" y="51"> color: #F46C43;</tspan> <tspan x="18" y="70"> }</tspan></text></g></svg>
```
That looks like:
![image](https://user-images.githubusercontent.com/32563455/55484077-83226880-5630-11e9-85d6-23773cc7adb8.png)

Does anybody know how to fix this?

**Comment by vvscode** [comment]
parse and decode urls? ))

I mean just write a script to do that. Any other proposals?

**Comment by zenby** [comment]
Closed due to https://github.com/memory-cards/cards/pull/14
